version: 2
jobs:
  test_house_prices_model:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - run:
          name: Runnning tests
          command: |
            virtualenv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r packages/houseprices_model/requirements.txt
            python packages/houseprices_model/houseprices_model/train_pipeline.py
            py.test -vv packages/houseprices_model/tests
workflows:
  version: 2
  test-all:
    jobs:
      - test_house_prices_model